name = "FF 1.21.8"
author = "Myster"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f05f92114747e32b32a8e700da7cefde3aff68a2e0f3ca6c73b54c5aa3e5bd17"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
