name = "FF 1.21.8"
author = "Myster"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de868bc257957f5914bf9f4dbd67d0e6f333bb1a66d4f8716759d4fbaf71ea54"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
