name = "FF 1.21.8"
author = "Myster"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15dcd8c093b8915697fa8fdacc2302ac726e313716615c7ae9b956762e24c275"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
