name = "FF 1.21.8"
author = "Myster"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11735e497da5e807f3ea2569d15383d57b918b3ecea5cfc15cfda9273512877d"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
